version: '3'
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://host.docker.internal:3100:3100/loki/api/v1/push"

services:
  mariadb:
    <<: *logging
    container_name: mariadb
    build:
      context: mariadb/.
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - /home/mariadb/:/etc/mysql/conf.d/
    env_file:
      - custom/db.env
    networks:
      - backend_prod

  sql_migrations:
    <<: *logging
    container_name: sql_migrations
    build: sql_migrations/.
    restart: on-failure:5
    env_file:
      - custom/bot.env
    networks:
      - backend_prod
    depends_on:
      - mariadb

  python_discord_bot:
    <<: *logging
    container_name: python_discord_bot
    build: python_discord_bot/.
    restart: always
    env_file:
      - custom/bot.env
    networks:
      - backend_prod
      - world
    depends_on:
      - mariadb
      - sql_migrations

  python_bot_frontend:
    <<: *logging
    container_name: python_bot_frontend
    build: python_flask/.
    restart: always
    env_file:
      - custom/bot.env
    networks:
      - backend_prod
    labels:
      - traefik.enable=true
      - traefik.http.routers.python_bot_frontend.rule=Host(`bot.REPLACE_ME_DOMAIN`)
      - traefik.http.routers.python_bot_frontend.entrypoints=websecure
      - traefik.http.routers.python_bot_frontend.tls.certresolver=dockerssl
      - traefik.http.services.python_bot_frontend.loadbalancer.server.port=5000
      - traefik.http.routers.python_bot_frontend.middlewares=main_auth
    depends_on:
      - mariadb
      - sql_migrations

  whoami:
    <<: *logging
    container_name: simple-service
    image: traefik/whoami
    networks:
      - backend_prod
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.REPLACE_ME_DOMAIN`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls.certresolver=dockerssl
      - traefik.http.routers.whoami.middlewares=main_auth
      - traefik.http.services.whoami.loadbalancer.server.port=80

volumes:
  mysql-data:

networks:
  backend_prod:
    external: true
  backend_staging:
    external: true
  world:
    external: true