global:
  scrape_interval:     10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

rule_files:
  - '/alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'db_exporter'
    static_configs:
      - targets: ['db_exporter:9104']
  - job_name: 'promcord'  
    static_configs:
      - targets: ['host.docker.internal:9590']
  - job_name: 'data_sql_exporter'  
    static_configs:
      - targets: ['query_exporter:9560']
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:5008']