USE REPLACE_ME_DB_NAME;
CREATE USER 'exporter'@'%' IDENTIFIED BY 'REPLACE_ME_EXPORTER_PASS' WITH MAX_USER_CONNECTIONS 2;
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%';
FLUSH PRIVILEGES;
CREATE TABLE IF NOT EXISTS example_table (example_column1 INT(15), example_column2 INT(15));
INSERT INTO example_table VALUES (1, 2);
INSERT INTO example_table VALUES (3, 4);
INSERT INTO example_table VALUES (1, 5);