{
 "title": "promcord-NEW",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "guild", "label": "Guild", "query": { "query": "promcord_msg_count_total" } },
   { "name": "user", "label": "User", "query": { "query": "promcord_msg_count_total" } },
   { "name": "game", "label": "Game", "query": { "query": "promcord_game_usage" } }
  ]
 },
 "panels": [
  {
   "title": "Discord Gateway Ping",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "promcord_discord_ping_websocket"
    }
   ]
  },
  {
   "title": "Server Boost Status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "promcord_booster_count{guild=~\"$guild\"}",
     "legendFormat": "Server Boost Count"
    }
   ]
  },
  {
   "title": "Total Messages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(promcord_msg_count_total{guild=~\"$guild\"}) by (guild)",
     "legendFormat": "Messagecount {{guild}}"
    }
   ]
  },
  {
   "title": "Message Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(promcord_msg_count_total{guild=~\"$guild\"}[$__interval])) by (guild)",
     "legendFormat": "Messageactivity {{guild}}"
    }
   ]
  },
  {
   "title": "Total Members",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(promcord_member_count{guild=~\"$guild\"})"
    }
   ]
  },
  {
   "title": "Bots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(promcord_bot_count{guild=~\"$guild\"})"
    }
   ]
  },
  {
   "title": "Humans",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(promcord_member_count{guild=~\"$guild\"} ) - sum(promcord_bot_count{guild=~\"$guild\"} ) "
    }
   ]
  },
  {
   "title": "Online Members",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(promcord_member_online{guild=~\"$guild\"})"
    }
   ]
  },
  {
   "title": "Messages by Top 25 User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(25, sum(promcord_msg_count_total{user=~\"$user\",guild=~\"$guild\"})by(user))",
     "legendFormat": "User {{user}}"
    }
   ]
  },
  {
   "title": "Top 25 Voice Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(25, sum(promcord_voice_time{user=~\"$user\",guild=~\"$guild\"}/60)by(user))",
     "legendFormat": "User {{ user }}"
    }
   ]
  },
  {
   "title": "Voice Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(promcord_voice_time{user=~\"$user\",guild=~\"$guild\"})"
    }
   ]
  },
  {
   "title": "Active Users (1d)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(changes(promcord_msg_count_total{user=~\"$user\",guild=~\"$guild\"}[1d]) > 0) by (user))"
    }
   ]
  },
  {
   "title": "Active Users (1w)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(changes(promcord_msg_count_total{user=~\"$user\",guild=~\"$guild\"}[1w]) > 0) by (user))"
    }
   ]
  }
 ]
}