{
 "title": "Docker and system monitoring",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "containergroup", "label": "Container Group", "query": { "query": "label_values(container_group)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": {
     "query": "label_values(node_boot_time, instance)"
    }
   },
   {
    "name": "node",
    "label": "IP",
    "query": {
     "query": "label_values(node_exporter_build_info{name=~'$name'},instance)"
    }
   },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "name",
    "label": "CPU Name",
    "query": {
     "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Mermory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Available Memory"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes {job=\"node-exporter\", instance=~\".*9100\", device=~\"/dev/mapper/vg-root\", mountpoint!=\"/var/lib/docker/aufs\"} - node_filesystem_free_bytes{job=\"node-exporter\", instance=~\".*9100\", device=~\"/dev/mapper/vg-root\", mountpoint!=\"/var/lib/docker/aufs\"}) / node_filesystem_size_bytes{job=\"node-exporter\", instance=~\".*9100\", device=~\"/dev/mapper/vg-root\", mountpoint!=\"/var/lib/docker/aufs\"} )"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(ALERTS)" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "ALERTS_FOR_STATE{}" }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-sum(rate(node_disk_reads_completed_total[$interval])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total[$interval])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU GHz by Core",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_cpu_scaling_frequency_hertz{job=\"node-exporter\"}) by (cpu)",
     "legendFormat": "Core {{ cpu }}"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes {job=\"node-exporter\", instance=~\".*9100\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"}) ",
     "legendFormat": "Free Storage"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  }
 ]
}