{
 "title": "Loki Dashboard quick search new",
 "description": "Loki logs panel with prometheus variables ",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "container_name", "query": "label_values(container_name)" },
   { "name": "search" }
  ]
 },
 "panels": [
  { "title": "Log graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% of logs with \"error\" or \"fail\" ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=~\"$container_name\"} |~\"(?i)fail|error\" !~\"query.*status=200\" | __error__=\"\"[$__range]))) / (sum(count_over_time(({container_name=~\"$container_name\"} [$__range]))))*100"
    }
   ]
  },
  {
   "title": "% of logs sent to stderr",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=~\"$container_name\"} | source=~\"stderr\" | container_name != \"loki\" | __error__=\"\"[$__range]))) / (sum(count_over_time(({container_name=~\"$container_name\"} [$__range]))))*100"
    }
   ]
  },
  {
   "title": "Total Logs without \"error\" or \"fail\" ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=~\"$container_name\"}[$__range] !~\"(?i)fail\" !~ \"(?i)error\"))"
    }
   ]
  },
  {
   "title": "Total Logs with \"error\" or \"fail\" ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=~\"$container_name\"}[$__range] |~\"(?i)fail|error\" !~ \"query.*status=200\"))"
    }
   ]
  },
  {
   "title": "Total Logs sent to stderr",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=~\"$container_name\"}[$__range] | source =~ \"stderr\" | container_name != \"loki\"))"
    }
   ]
  },
  {
   "title": "Total Logs sent to stdout",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=~\"$container_name\"}[$__range] | source =~ \"stdout\" or container_name =~ \"loki\"))"
    }
   ]
  },
  {
   "title": "Total logs without \"error\" or \"fail\" ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container_name) (count_over_time({container_name=~\"$container_name\"}[$__range] !~\"(?i)fail\" !~ \"(?i)error\"))",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Total logs on stdout",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container_name) (count_over_time({container_name=~\"$container_name\"}[$__range] | source =~\"stdout\" or container_name =~ \"loki\"))",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Total logs with \"error\" or \"fail\" ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container_name) (count_over_time({container_name=~\"$container_name\"}[$__range] |~\"(?i)fail|error\" !~ \"query.*status=200\"))",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Total logs on stderr",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container_name) (count_over_time({container_name=~\"$container_name\"}[$__range] | source =~\"stderr\" | container_name != \"loki\"))",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  { "title": "Log Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Logs Panel",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{container_name=~\"$container_name\"} |~ \"$search\"",
     "legendFormat": "{{ container_name }}"
    }
   ]
  }
 ]
}